name: Deploy ke GitHub Pages
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Inject Firebase Config
        run: |
          echo "window.__FIREBASE_CONFIG__ = ${{ secrets.FIREBASE_CONFIG }};" > firebase-config.js

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
